### ISSUE TITLE
使用plugin 的时候，整个bot均无法使用帮助

### ISSUE THREAD

**Issue by PierceLiu** [117503445/yunzai-bot-web#11]
![image](https://github.com/117503445/yunzai-bot-web/assets/57214772/8bb166c9-45b9-46d2-9575-dc23ad76025b)
添加了这些plugin后，无法使用，且帮助也无法使用

**Comment by 117503445** [comment]
我感觉是因为 genshin 是默认插件， `#帮助` 也是由 genshin 提供的。你把文件夹挂载进去，可能就导致 genshin 无法使用了。

**Comment by PierceLiu** [comment]
收到。等回复吧。

**Comment by PierceLiu** [comment]
> 我感觉是因为 genshin 是默认插件， `#帮助` 也是由 genshin 提供的。你把文件夹挂载进去，可能就导致 genshin 无法使用了。

已经解决了，去除掉“genshin”,"yunzai-c-v-plugin"之后是可以正常运行了，另外想问一下，使用了逍遥插件后可以添加stoken以防止cookie失效，但是在添加stoken时，bot回复依旧为“请私聊发送”

**Comment by 117503445** [comment]
见 #12
