### ISSUE TITLE
QQ 消息改为私聊格式

### ISSUE THREAD

**Issue by 117503445** [117503445/yunzai-bot-web#12]
目前 YunZai-Bot-Web 给 Bot 传递的 QQ 消息都为 group 类型，导致部分插件无法使用。考虑把 QQ 消息 改成私聊类型。

需求见 #11

**Comment by PierceLiu** [comment]
是否可以详细的说一下操作流程呢，主要没找到咱们的配置文件，而且也不太会使用docker

**Comment by 117503445** [comment]
容器中 `/root/Yunzai-Bot/lib/tools/server.js` 是 Web 后端的代码

其中

```js
let e = {
    "test": true,
    "self_id": 10000,
    "time": 1676913595310,
    "post_type": "message",
    "message_type": "friend",
    "sub_type": "normal",
    "group_id": 826198224,
    "group_name": "测试群",
    "user_id": qq,
    "anonymous": null,
    "message": [
        {
            "type": "text",
            "text": prompt
        }
    ],
    "raw_message": "#uid",
    "font": "微软雅黑",
    "sender": {
        "user_id": qq,
        "nickname": "测试",
        "card": "this_is_card",
        "sex": "male",
        "age": 0,
        "area": "unknown",
        "level": 2,
        "role": "owner",
        "title": ""
    },
    "group": {
        "mute_left": 0
    },
    "friend": {},
    "message_id": "JzHU0DACliIAAAD3RzTh1WBOIC48"
}
```

把网页上的消息转换为 QQ 消息，然后送进 Yunzai-Bot 内核

你可以看一看 逍遥插件 中是如何判断是否为群聊消息的，然后修改这部分代码即可。


具体的，因为改完代码还要加载比较麻烦，你可以先把 `docker-compose.yml` 中添加

```yml
entrypoint: /bin/bash
stdin_open: true # docker run -i
tty: true        # docker run -t
```

然后就能 attach 到容器的 shell 中，修改完代码，再 `node ./lib/tools/server.js` 即可验证效果

我本来想直接搞定这个需求的，打算登录原版 Yunzai-Bot 后，打印出私聊消息 e 的结构。但是现在我登不上去，参考 <https://zhuanlan.zhihu.com/p/612320316> 可能是因为 Yunzai-Bot 确实已经无法登录了。所以我就无法得到 e 的结构体了：（

**Comment by PierceLiu** [comment]
十分感谢,我去尝试一下,感谢感谢

**Comment by typenoob** [comment]
![image](https://github.com/117503445/yunzai-bot-web/assets/61347081/28f54823-ba12-4679-a911-fae8da37b594)
来自：Yunzai-Bot源码
message_type的值是否应该为private，而不是friend？

**Comment by 117503445** [comment]
![image](https://github.com/117503445/yunzai-bot-web/assets/21152034/f5fa5279-1f0d-492a-bd9e-a485bdce56f8)

你尝试过这个的修改了吗

> ![image](https://user-images.githubusercontent.com/61347081/278511190-28f54823-ba12-4679-a911-fae8da37b594.png) 来自：Yunzai-Bot源码 message_type的值是否应该为private，而不是friend？

**Comment by typenoob** [comment]
> ![image](https://user-images.githubusercontent.com/21152034/278533843-f5fa5279-1f0d-492a-bd9e-a485bdce56f8.png)
> 
> 你尝试过这个的修改了吗
> 
> > ![image](https://user-images.githubusercontent.com/61347081/278511190-28f54823-ba12-4679-a911-fae8da37b594.png) 来自：Yunzai-Bot源码 message_type的值是否应该为private，而不是friend？

修改了，修改前发送抽卡链接提示要私聊发送，修改后可以了
