### ISSUE TITLE
米游社cookie绑定异常

### ISSUE THREAD

**Issue by Cystee** [117503445/yunzai-bot-web#13]
如图所示：
![image](https://github.com/117503445/yunzai-bot-web/assets/61391190/cb836518-102b-4171-a314-8255396bd90f)

**Comment by 117503445** [comment]
感觉是这个指令的问题，你直接 `#纳西妲圣遗物` 应该是可以正常显示的

**Comment by Cystee** [comment]
的确可以，但是实际上ck还是用不了
![image](https://github.com/117503445/yunzai-bot-web/assets/61391190/4c887e8e-3f2d-48a0-85af-366db424607e)
另外，这种方式也不行
![image](https://github.com/117503445/yunzai-bot-web/assets/61391190/158c92b6-2638-448a-b815-7c158ee8c4b6)
