### ISSUE TITLE
内置的喵喵插件如何更新呢

### ISSUE THREAD

**Issue by GeeRan-Alpha** [117503445/yunzai-bot-web#14]
试了下#喵喵更新好像并不能进行插件的更新

**Comment by 117503445** [comment]
目前更新的逻辑是 `yunzai-bot-web` 代码更新 or 手动触发，通过 GitHub Action 拉取最新的喵喵插件并构建、推送镜像。目前已更新到最新的 2.4.2 版本。

没有做成全自动更新，是因为我担心喵喵插件和 `yunzai-bot-web` 产生兼容性问题，导致无法使用。

以后如果你认为新版本的喵喵插件具有你想要的功能，可以在这个 issue 中评论提醒我去更新。

**Comment by rukiuss1** [comment]
我尝试了#meowmiaoupdate，但它似乎没有更新插件。如何更新到最新版本2.4.5？

**Comment by 117503445** [comment]
> 我尝试了#meowmiaoupdate，但它似乎没有更新插件。如何更新到最新版本2.4.5？

目前插件的更新只能通过我这边触发。现在已经更新到 2.4.5 了。

**Comment by rukiuss1** [comment]
你说更新到了2.4.5，但是即使你使用#喵喵更新命令，它仍然是2.4.3版本，即使你重新启动，它仍然是2.4.3版本。我该如何继续更新？

**Comment by 117503445** [comment]
> 你说更新到了2.4.5，但是即使你使用#喵喵更新命令，它仍然是2.4.3版本，即使你重新启动，它仍然是2.4.3版本。我该如何继续更新？

`#喵喵更新` 是没有用的。你需要拉取最新的镜像再重新启动，比如 `docker compose pull && docker compose up -d`

**Comment by rukiuss1** [comment]
我在哪里可以获得最新的图像？

**Comment by 117503445** [comment]
`docker compose pull` 就是拉取 `docker-compose.yml` 里最新的 Image

然后 `docker compose up -d` 就会以新 Image 启动

**Comment by rukiuss1** [comment]
ubuntu:~/yunzai-bot-web$ docker compose down
[+] Running 3/3
 ✔ Container yunzai-bot-web-yunzai-web-1  Removed                                                                                                                                                                                                                                              
 ✔ Container yunzai-bot-web-redis-1       Removed                                                                                                                                                                                                                                               
 ✔ Network yunzai-bot-web_default         Removed                                                                                                                                                                                                                                               
ubuntu:~/yunzai-bot-web$ docker compose pull && docker compose up -d
[+] Pulling 2/2
 ✔ redis Pulled                                                                                                                                                                                                                                                                                 
 ✔ yunzai-web Pulled                                                                                                                                                                                                                                                                            
[+] Running 3/3
 ✔ Network yunzai-bot-web_default         Created                                                                                                                                                                                                                                              
 ✔ Container yunzai-bot-web-redis-1       Healthy                                                                                                                                                                                                                                               
 ✔ Container yunzai-bot-web-yunzai-web-1  Started                                                                                                                                                                                                                                                
ubuntu:~/yunzai-bot-web$ docker compose up -d
[+] Running 2/2
 ✔ Container yunzai-bot-web-redis-1       Healthy                                                                                                                                                                                                                                              
 ✔ Container yunzai-bot-web-yunzai-web-1  Running                                                                                                                                                                                                                                               
ubuntu:~/yunzai-bot-web$ 
尽管我按照上面的方式运行它，但它的版本是 2.4.3。这种时候我该怎么办？

**Comment by 117503445** [comment]
`docker images --no-trunc | grep 117503445/yunzai-web` 输出的镜像哈希是什么呀

**Comment by rukiuss1** [comment]
通过使用 docker-compose pull 下载镜像，然后再次运行 docker-compose up -d 解决了这个问题。感谢您的快速回复。
