### ISSUE TITLE
关于通过json文件导入抽卡记录

### ISSUE THREAD

**Issue by nofadeaway** [117503445/yunzai-bot-web#15]
您好！请问这个可以像原本的云仔那样发送或者excel来导入抽卡记录吗？我尝试了复制其中的文本信息，好像不行。

**Comment by 117503445** [comment]
应该不行，现在 `yunzai-bot-web` 只向 `yunzai-bot` 模拟了普通的文字消息，但是 QQ 的文件传输消息应该是另一种数据结构，所以 `yunzai-bot-web` 应该不支持文件传输消息，暂时也没有支持的打算。

你要实现这个需求的话，可能更简便的方法是看看 `yunzai-bot` 里面哪个方法是处理抽卡记录文件的，然后在后端再开个接口，直接打通到这个处理方法上去。然后你直接发送 HTTP 请求把抽卡记录文件传进去（因为前端如果要支持发送文件也是个麻烦事）。
