### ISSUE TITLE
能提供平常的WEB版本部署吗

### ISSUE THREAD

**Issue by xingyunlee12138** [117503445/yunzai-bot-web#17]
能直接改成不需要docker的方式不，就像个正常网页部署在服务器上，或者本地项目，用反代访问

**Comment by 117503445** [comment]
我感觉非常麻烦，要配各种环境，还要做很多文本的替换。

当然，如果你有需求的话，就跟着 `Dockerfile` 和 `patch/script/patch.sh` 一步步做就行了。
