### ISSUE TITLE
为什么没有攻略的图片呀

### ISSUE THREAD

**Issue by FangXiaoyang** [117503445/yunzai-bot-web#19]
大佬能告诉一下 为什么#XX攻略是不能生成图片的啊

**Comment by B77TECH** [comment]
oicq的msg里图片支持Buffer和string等格式, 这里server.js只处理了Buffer的情况
https://github.com/117503445/yunzai-bot-web/blob/db056100c899d53f052f191613966f08a2024d13/patch/template/server.js#L127C59-L127C59

插件中使用puppeteer实时渲染的图片没有问题，但使用segment.image('file://xxx') 或 segment.image('http://xxx') 回复图片会出现此错误

解决方法可以自己修改插件从文件读入Buffer再回复，或者修改server.js的处理逻辑重新打包镜像

关联 #10
