### ISSUE TITLE
怎么支持ARM处理器

### ISSUE THREAD

**Issue by xingyunlee12138** [117503445/yunzai-bot-web#21]
yunzai-web The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
研究了半天，终于运行了，但是好像不支持ARM,求修改支持下，白嫖甲骨文用户表示 需要下

**Comment by 117503445** [comment]
目前 Docker 镜像是以 ArchLinux 为 Base Image 的，但是 ArchLinux 没有官方支持的 ARM64 版本，所以目前不能很方便的迁移到 ARM64 上。

你可以考虑根据 Dockerfile 的内容，更换 Base Image 后再试试

**Comment by 117503445** [comment]
#35 添加了 ARM64 支持，可以试一下
