### ISSUE TITLE
使用docker-compose up -d构建时 出现Restart（139）bug

### ISSUE THREAD

**Issue by PierceLiu** [117503445/yunzai-bot-web#23]
![image](https://github.com/117503445/yunzai-bot-web/assets/57214772/7c0221b3-9664-4424-ae36-052e63829a6d)
以下时docker logs 的错误信息
![image](https://github.com/117503445/yunzai-bot-web/assets/57214772/cd724d3b-1f19-457f-b221-824f2f401eb6)

**Comment by 117503445** [comment]
我这边运行起来是好的..

请提供更多信息，比如 镜像哈希，完整的 Docker 日志，机器信息，剩余内存之类的

**Comment by PierceLiu** [comment]
收到。等回复吧。

**Comment by PierceLiu** [comment]
剩余内存，这个是已经打开docker 的时候
![image](https://github.com/117503445/yunzai-bot-web/assets/57214772/4a820a37-b285-4705-8725-4519e8e0c8ba)
机器信息
![image](https://github.com/117503445/yunzai-bot-web/assets/57214772/23bd3b19-5876-42dd-8ba6-babca03a1969)
镜像的话就是用的github里面的readme里面的内容，docker日志 完整导出我需要研究一下

**Comment by 117503445** [comment]
可以通过 `docker images` 查看镜像信息，我想确认 `yunzai-web` 镜像的 `IMAGE ID`

**Comment by PierceLiu** [comment]
![image](https://github.com/117503445/yunzai-bot-web/assets/57214772/6038da1a-e961-42a0-a9b9-94dd9466e5ec)

**Comment by 117503445** [comment]
`IMAGE ID` 没问题

**Comment by 117503445** [comment]
你可以先 `docker compose down`, 再 `docker compose up -d`

开始重启的时候，`docker logs yunzai-web > 1.txt`，然后把 `1.txt` 发上来

**Comment by PierceLiu** [comment]
使用docker logs dockerID > 1.txt后 文件被创建，但是里面并无任何内容

**Comment by 117503445** [comment]
直接运行 `docker logs ContainerID` 呢

**Comment by PierceLiu** [comment]
也是没有的 我这边直接把terminal里面的log信息复制一下放在文档里面您看一下吧
[1.txt](https://github.com/117503445/yunzai-bot-web/files/12121804/1.txt)

**Comment by 117503445** [comment]
通过搜索 `node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.` 看上去是比较通用的问题，你试一下 下列链接 能否解决问题

<https://github.com/nodejs/node/issues/43064>
<https://github.com/koush/scrypted/issues/875>

**Comment by PierceLiu** [comment]
这边还是并未解决这个问题，麻烦问下你用的docker的版本和docker-compose的版本呢， 我这边的是docker18.03.1-ce
，docker-compose 是v2.20.0

**Comment by 117503445** [comment]
`docker info` 输出

```sh
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.20.2
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 9
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0cae528dd6cb557f7201036e9f43420650207b58.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.4.4-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
```

**Comment by PierceLiu** [comment]
我重新装一下docker  换一个更高版本的尝试一下

**Comment by PierceLiu** [comment]
更新了docker的版本后，现在使用的24.0.5 是没有任何使用问题 直接就可以打开，所以有理由怀疑是因为docker版本过低的问题，感谢，问题已经解决
