### ISSUE TITLE
攻略的图片都加载不出来

### ISSUE THREAD

**Issue by WangDanpeng** [117503445/yunzai-bot-web#25]
<img width="443" alt="image" src="https://github.com/117503445/yunzai-bot-web/assets/20870505/43f7f485-f3e9-4691-97cd-c8f35f0ef02f">
查询数据都正常, 攻略的出不来是什么问题

**Comment by WangDanpeng** [comment]
日志
{"level":30,"time":1690275911085,"pid":1,"hostname":"dd0072afc052","reqId":"req-33","res":{"statusCode":200},"msg":"stream closed prematurely"}

**Comment by 117503445** [comment]
fixed
