### ISSUE TITLE
安装逍遥插件后，发送#扫码登录，无回复

### ISSUE THREAD

**Issue by dxx4396** [117503445/yunzai-bot-web#26]
![image](https://github.com/117503445/yunzai-bot-web/assets/51263226/eadcaa6c-19c9-4ed3-86c7-3a4d4132a80d)

**Comment by 117503445** [comment]
一个问题是 逍遥插件 发送了数组，`Yunzai-Bot-Web` 不能很好的处理这种结构

最主要的问题是 逍遥插件 在 `#扫码登陆` 的时候会阻塞住。而现在 `Yunzai-Bot-Web` 的前后端是通过 HTTP 进行同步调用的，无法支持这种情况。
