### ISSUE TITLE
code space 运行异常

### ISSUE THREAD

**Issue by wuyilingwei** [117503445/yunzai-bot-web#27]
[master][/workspaces/yunzai-bot-web]$ docker compose up -d
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
请问该如何解决

**Comment by 117503445** [comment]
你这是在容器内部运行的 `docker compose up -d` 吗

**Comment by wuyilingwei** [comment]
> 你这是在容器内部运行的 `docker compose up -d` 吗

呃，docker不太懂，直接在终端中运行不行吗？

**Comment by 117503445** [comment]
哦哦，那应该是你 Docker 环境没配好。Docker 客户端无法连接到 Docker 服务端，最常见的原因是没给普通权限账户配置 Docker 的权限，也可能是 Docker 服务端挂了。你可以参考 [官方文档](https://docs.docker.com/engine/install/) 进行安装。

**Comment by wuyilingwei** [comment]
> 哦哦，那应该是你 Docker 环境没配好。Docker 客户端无法连接到 Docker 服务端，最常见的原因是没给普通权限账户配置 Docker 的权限，也可能是 Docker 服务端挂了。你可以参考 [官方文档](https://docs.docker.com/engine/install/) 进行安装。

code space不行吗？我看项目中有code space的配置文件以为可以的@.@

**Comment by 117503445** [comment]
你是想开发调试还是部署呀

**Comment by wuyilingwei** [comment]
> 你是想开发调试还是部署呀

临时部署，因为docker真的没用过@。@，没想到code space的代码用不了，也许是code space的问题

**Comment by 117503445** [comment]
只是想部署的话，你自己配置好 Docker 环境，然后 `docker compose up -d` 就可以了。

.devcontainer 我是用来定义 VSCode 的开发容器功能的，而且没有关注过与 CodeSpace 的兼容性。总之就是你只部署不开发，那么就按照 README 一步步走就行了。
