### ISSUE TITLE
如何修改redis服务器地址

### ISSUE THREAD

**Issue by Omoinemie** [117503445/yunzai-bot-web#28]
docker的redis和其他容器版本冲突，导致容器无法启动，如何设置独立redis版的，我在物理机上安装的redis，希望能在模板中直接设置redis地址

**Comment by 117503445** [comment]
为什么 yunzai-bot-web 的 Redis 会和其他容器冲突呀，Docker 的设计理论上来说就是为了避免这种冲突的

**Comment by Omoinemie** [comment]
> 为什么 yunzai-bot-web 的 Redis 会和其他容器冲突呀，Docker 的设计理论上来说就是为了避免这种冲突的

那为什么重启一次服务器容器就启动不了了，一直提示redis无法连接
![image](https://github.com/117503445/yunzai-bot-web/assets/31991443/9027e3ec-b417-4cc4-8a27-806290ed88f5)
![image](https://github.com/117503445/yunzai-bot-web/assets/31991443/f491052a-fd3c-4cb6-8702-3170e41dffc5)

**Comment by 117503445** [comment]
你看 Redis 日志，是因为没有权限读取 rdb 文件。你可以去排查一下 Redis 容器的用户问题。

实在搞不定的话，你可以修改 Yunzai-Bot 容器的 `/root/Yunzai-Bot/config/config/redis.yaml`

现在的 `redis.yaml` 的内容是

```sh
# redis地址
host: redis
# redis端口
port: 6379 
# redis密码，没有密码可以为空    
password: 
# redis数据库    
db: 0
```

你把 host 改成自己的，然后再把这个文件挂载进去就行了。
