### ISSUE TITLE
镜像稍微有点大哎，有办法优化一下吗

### ISSUE THREAD

**Issue by typenoob** [117503445/yunzai-bot-web#31]

**Comment by 117503445** [comment]
问题在于依赖挺多的。尤其是玩家圣遗物评分图这种功能，是先准备好 HTML，然后调用浏览器渲染成图片。浏览器又依赖一大堆库，最后镜像体积很难有数量级的缩小。

你有兴趣的话，可以尝试使用 [Google distroless 镜像](https://github.com/GoogleContainerTools/distroless/blob/main/nodejs/README.md)。最后体积肯定会比现在基于 ArchLinux 的要小，而且也能支持 ARM64 #21  了。

**Comment by typenoob** [comment]
我用alpine构建了一个1g不到的，有空试试看能不能运行

**Comment by typenoob** [comment]
`docker pull docker.nju.edu.cn/typenoob/yunzai-web && docker image tag docker.nju.edu.cn/typenoob/yunzai-web 117503445/yunzai-web`
`docker pull docker.nju.edu.cn/typenoob/redis:alpine && docker image tag docker.nju.edu.cn/typenoob/redis:alpine redis:alpine`
armv8和小闪存设备可以在`docker compose up -d`之前拉取我的镜像。（神奇的是我试了一下它在x64上也能运行。）

**Comment by 117503445** [comment]
#35 进行了更新，为了防止潜在的插件兼容性问题，最后还是参照原项目，用了 node:lts-slim
