### ISSUE TITLE
希望能支持GT-Manual手动验证

### ISSUE THREAD

**Issue by Kratosmax** [117503445/yunzai-bot-web#32]
基本上所有的米游社功能都会遇上：米游社查询遇到验证码，请稍后再试
我尝试自己手动安装了这个插件，但失败了，希望大佬能看看
https://gitee.com/QQ1146638442/GT-Manual

**Comment by 117503445** [comment]
你可以下载胡桃工具箱，登录自己账号后，实时便笺 - 验证当前用户与角色，就能解决米游社账号的风控问题了
