### ISSUE TITLE
Miao Plugin 2.5.2 Update 这什么时候可以实现

### ISSUE THREAD

**Issue by rukiuss1** [117503445/yunzai-bot-web#33]
我正在使用你制作的网页版，非常好。
芙宁娜 我想尝试使用计算器。请更新。

**Comment by 117503445** [comment]
已升级

其实你可以参考 <https://github.com/117503445/yunzai-bot-web#%E6%9B%B4%E6%96%B0%E9%95%9C%E5%83%8F>, 使用 nightly tag，就能使用到最新的插件了。
