### ISSUE TITLE
user plugins should always override plugins

### ISSUE THREAD

**Issue by stkevintan** [117503445/yunzai-bot-web#38]
https://github.com/117503445/yunzai-bot-web/blob/796d1376c927467808038c9f1592ecc88e134085/src/Yunzai-Bot/docker-entrypoint.py#L11C1-L12C20

In this case, the docker container will copy miao-plugin from user-plugins to plugins at first run but will exit abnormally on second run except attaching to the container then delete the plugins/miao-plugin manually.

User never get a chance to update the plugin's version or apply a ad-hoc fix (like https://github.com/yoimiya-kokomi/miao-plugin/issues/519)

**Comment by stkevintan** [comment]
perhaps, the best way is soft link

**Comment by 117503445** [comment]
Fixed, thank you very much for the suggestion
