### ISSUE TITLE
插件安装 & 管理员权限

### ISSUE THREAD

**Issue by hbj2457** [117503445/yunzai-bot-web#4]
请让docker映射data，插件等文件
支持控制台docker exec -it yunzai-web /bin/sh
还有怎么给予管理员权限(可以整个管理员输入密码登录)

**Comment by 117503445** [comment]
> 请让docker映射data，插件等文件

我空的时候看看

> 支持控制台 docker exec -it yunzai-web /bin/sh

现在可以正常运行此命令的呀

> 还有怎么给予管理员权限(可以整个管理员输入密码登录)

管理员权限这方面我去看看。登录方面，你是希望部署一个 yunzai-bot-web 实例可以服务多个用户吗

**Comment by hbj2457** [comment]
多个用户我倒没这么想，可以有的，就是希望有一个管理员登录的地方或者说一个按钮，点击之后输入密码，然后就进入管理员模式，然后有一些基本的功能，比如修改管理员密码，然后也可以用管理员权限执行云崽的指令

**Comment by 117503445** [comment]
安装插件的方法已补充至 README

**Comment by 117503445** [comment]
现在默认就是管理员权限

**Comment by 8852690** [comment]
这个看着主要还是个人使用，相较于云崽缺少了用户控制的功能，会出现所有人都能执行master权限命令的情况，不适合大范围使用，而且如果有其他人使用，还可以看到前面的人的数据。

**Comment by 117503445** [comment]
> 这个看着主要还是个人使用，相较于云崽缺少了用户控制的功能，会出现所有人都能执行master权限命令的情况，不适合大范围使用，而且如果有其他人使用，还可以看到前面的人的数据。

是的，因为 云崽 的权限控制是和 QQ 耦合的。我移除了 QQ 依赖以后，云崽会认为所有消息都来自管理员的QQ账号，从而失去了权限的功能。

解决方案就是在 web 层再加一套用户管理。但我觉得 `yunzai-bot-web` 已经大幅降低了部署难度，每个人自己部署一份又安全又简洁，所以不打算增添用户管理的功能。
