### ISSUE TITLE
迁移到 miao-yunzai

### ISSUE THREAD

**Issue by Eiranya** [117503445/yunzai-bot-web#5]
这是基于原版云崽吗？原版云崽好像不维护了，可以迁移到miao-yunzai吗？

**Comment by 117503445** [comment]
目前是基于原版云崽的

我的需求就是使用 miao-plugin，miao-yunzai 似乎并没有带来新的功能点，因此短时间内我没有升级至 miao-yunzai 的动力

长时间来看，miao-yunzai 提到会对接其他 IM，到时候可能都不用 yunzai-bot-web 了

总之就是，如果短期内 miao-yunzai 出现新的重要功能点的时候，我会尝试迁移的
