### ISSUE TITLE
不兼容 Arm & 多用户支持

### ISSUE THREAD

**Issue by LowValueTarget777** [117503445/yunzai-bot-web#6]
是不是不兼容树莓派4，用树莓派4搭建docker容器一直在重启
然后看日志是exec /usr/sbin/node: exec format error
![image](https://user-images.githubusercontent.com/42969918/233116754-74faafef-bc14-49cc-9c1b-e708cf6924b0.png)

**Comment by LowValueTarget777** [comment]
在我使用qemu模拟amd64启动之后连接不了redis
![image](https://user-images.githubusercontent.com/42969918/233134895-9277fa59-d942-4986-bba3-6d0502b94bba.png)

**Comment by LowValueTarget777** [comment]
修改了redis.js代码 先启动redis再连接终于是连进去了，但是现在启动不了chromium...
![image](https://user-images.githubusercontent.com/42969918/233170966-32cfa2d4-0c36-4f1f-9a35-aaf042093bbd.png)
并且功能都无法使用
![image](https://user-images.githubusercontent.com/42969918/233171514-2ee3ab58-08c8-4d48-b220-96025eb0013b.png)
![image](https://user-images.githubusercontent.com/42969918/233171886-ce02ac43-c645-42c5-8801-56b66bf0b0ef.png)

**Comment by 117503445** [comment]
不好意思，是没有考虑到对 Arm 的支持

**Comment by 117503445** [comment]
> 修改了redis.js代码 先启动redis再连接终于是连进去了，但是现在启动不了chromium... ![image](https://user-images.githubusercontent.com/42969918/233170966-32cfa2d4-0c36-4f1f-9a35-aaf042093bbd.png) 并且功能都无法使用 ![image](https://user-images.githubusercontent.com/42969918/233171514-2ee3ab58-08c8-4d48-b220-96025eb0013b.png) ![image](https://user-images.githubusercontent.com/42969918/233171886-ce02ac43-c645-42c5-8801-56b66bf0b0ef.png)

你需要使用 `#帮助`。 Yunzai-Bot 的大部分命令也都是要以 `#` 开头的。不过 Chromium 无法启动的话，我感觉会在渲染图片的时候出问题。

**Comment by LowValueTarget777** [comment]
命令带#也没有用
![image](https://user-images.githubusercontent.com/42969918/233253867-ba549253-4831-4f34-a19e-66739ed0c07a.png)
![image](https://user-images.githubusercontent.com/42969918/233253889-a98d6ec1-4b08-47a1-ad42-39c4731f3714.png)

**Comment by 117503445** [comment]
要不你试试裸安装 Yunzai-Bot 和 miao-plugin, 更方便安装相关依赖、调试

如果需要去除 QQ 依赖的话，你可以参考本项目的 `Dockerfile`

**Comment by LowValueTarget777** [comment]
我现在树莓派倒是有在运行着一个yunzai,但是因为在国外发送图片很慢，所以看到这个说看看web因该能很快的响应图片

**Comment by 117503445** [comment]
那你按照我的 `Dockerfile` 去除 QQ 依赖以后，应该就能排除掉 QQ 这一步的延迟了

另外就是，yunzai-web 只会返回 yunzai 内核 2s 内做出的回复，详细逻辑见 `Yunzai-Bot/lib/tools/server.js`，你把超时时间改大点可能有所帮助

**Comment by LowValueTarget777** [comment]
我现在没用docker  根据Dockerfile在本地搭了一个倒是能正常用，本来想build一个arm架构的镜像，但是chromium怎么也启动不起来，启动的时候说用snap安装，
![image](https://user-images.githubusercontent.com/42969918/233539043-01241db6-c69b-4050-b40d-c3a5dce6d245.png)
但是snap又有问题
![image](https://user-images.githubusercontent.com/42969918/233539109-c518c43a-aa16-4a82-bf87-fc4b98d15627.png)
暂时懒得搞了
顺便问一下能不能加一个简单的用户管理，搞一个简单的自定义数字区分用户就行，不懂node.js实在是搞不来

**Comment by 117503445** [comment]
用户管理 这个我看看怎么弄，我想到的实现方案是后端开启 Basic Auth，然后在配置文件中定义 Basic Auth 用户及对应的 QQ 号，这样就可以实现安全的多用户，且不影响前端（我也不太会前端

**Comment by 117503445** [comment]
顺便问一下你是想一个实例服务多个用户吗

**Comment by LowValueTarget777** [comment]
是的，大概十多个人吧

**Comment by 117503445** [comment]
好的，我有空实现一下

**Comment by LowValueTarget777** [comment]
十分感谢

**Comment by 117503445** [comment]
已经实现多用户了，但是我只有 1 个原神账号，你试试能不能用
