### ISSUE TITLE
是否可以在浏览器端渲染图片？

### ISSUE THREAD

**Issue by QyInvoLing** [117503445/yunzai-bot-web#7]
在容器内用chromium渲染图片再发出来的流量费有些高昂，或许可以让用户自己的浏览器来渲染

**Comment by 117503445** [comment]
主意是好主意，但是实现的话前后端都要改，工作量不小，还容易有兼容问题，我不是很想做

**Comment by QyInvoLing** [comment]
好的，如果这段时间我有空能写的话，我试着写，写好了提个pr
