### ISSUE TITLE
安装 TRSS-Plugin 存在问题 & Cookie 油猴插件

### ISSUE THREAD

**Issue by waterlemonrunning** [117503445/yunzai-bot-web#8]
想要安装的插件：https://gitee.com/TimeRainStarSky/TRSS-Plugin/
下载完成插件后，映射进plugins目录：
![image](https://user-images.githubusercontent.com/38038787/234373322-35cdf715-553b-422d-a677-17da2175d079.png)
之后运行 “docker compose up -d”, 在web聊天框中，无法加载出该插件的指令。

PS: 七胜召唤安装成功了。
![image](https://user-images.githubusercontent.com/38038787/234373816-eaed4415-9cea-4a82-a466-7ba2a45a10e3.png)

**Comment by waterlemonrunning** [comment]
看了下日志，发现可能是前端渲染的问题？不太确定，麻烦大佬帮忙看下：
![image](https://user-images.githubusercontent.com/38038787/234379361-d42de4ef-0b36-4ed6-9c13-26751f909dc1.png)
![image](https://user-images.githubusercontent.com/38038787/234379416-9399112f-3c78-434f-91e4-c9fff238ed19.png)

**Comment by 117503445** [comment]
我也尝试了一下，`系统测试` 命令是可用的，证明插件安装是成功的，其他功能我再想想办法。你主要想用哪些功能呀

**Comment by waterlemonrunning** [comment]
其实安装这个TRSS-Plugin主要是为了扫码登陆。。。
不过如果安装不了这类插件的话，也没事。

**Comment by 117503445** [comment]
针对登录这个需求，我觉得目前 cookie 的方式已经挺方便了，也很久不会失效。或者可以考虑开发油猴插件，在米游社 Web 端添加一个发送 cookie 至 yunzai-bot 的按钮，就更加便捷了

**Comment by waterlemonrunning** [comment]
也是，这个想法好，的确可以解决这个需求。

**Comment by 117503445** [comment]
油猴插件搞定了，你看看 README

**Comment by waterlemonrunning** [comment]
非常感谢，还有个无关紧要的需求：
有没有可能加一个邀请，现在添加他人使用需要改配置，比较麻烦。 如果可以直接让别人注册就好了。

**Comment by waterlemonrunning** [comment]
我测试了下，安装其他的插件，比如  Atlas， 返回图像时，也会出现图像返回失败的情况。
请问这是不是chatweb配置上有什么问题？
![image](https://user-images.githubusercontent.com/38038787/235621881-c802b634-1e0a-4bcd-bd58-7b569ead7b4a.png)
![image](https://user-images.githubusercontent.com/38038787/235630968-114c22cc-fad7-4b11-bf14-6e64ca2e3681.png)
![image](https://user-images.githubusercontent.com/38038787/235631769-48b9e12a-c591-4e0a-85bb-bef754776d42.png)

**Comment by 117503445** [comment]
这 2 个问题在新 issue 中进行讨论
