### ISSUE TITLE
允许用户注册

### ISSUE THREAD

**Issue by 117503445** [117503445/yunzai-bot-web#9]
目前多用户需要管理员手动创建用户的账号，能否让用户自己创建账号

原始需求见 #8

**Comment by 117503445** [comment]
@waterlemonrunning 这个功能可能近几天还无法完成开发，现在有个临时的解决方法，就是再写个后端，用户输入 username password qq 后，把这些字段写入配置文件，然后重启 yunzai-web

**Comment by waterlemonrunning** [comment]
感觉这样没必要。
我现在是ssh挂载config到本地文件夹，添加完后，重启docker，也能用。

**Comment by 117503445** [comment]
你的需求不是允许用户自己注册吗

**Comment by waterlemonrunning** [comment]
实现起来比较麻烦，也没必要做了。。。
